---
title: Nepal Typhoid Case Analysis 
author: Chris LeBoa
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(tableone)


# Parameters
file_redcap <-  "/Users/ChrisLeBoa/GitHub/typhoid_research/nepal_typhoid/data/cases/redcap/redcap_data_nepal.rds"
file_cases_gis <- "/Users/ChrisLeBoa/GitHub/typhoid_research/nepal_typhoid/data/cases/all_cases.shp"
ages_plot <- "/Users/ChrisLeBoa/GitHub/typhoid_research/nepal_typhoid/reports/cases_ages.png"
table_one <- "/Users/ChrisLeBoa/GitHub/typhoid_research/nepal_typhoid/reports/table_one.csv"

```

## Load Case Data 

```{r}

#Find arms of interest
read_rds(file_redcap) %>% 
  distinct(redcap_event_name)

#Create cases and case_cohort groupings 
cases <- 
  read_rds(file_redcap) %>% 
  filter(str_detect(redcap_event_name, "baseline_arm_1|first_visit_arm_2"))

case_cohort <- 
  read_rds(file_redcap) %>% 
  filter(
    str_detect(
      redcap_event_name,
      "baseline_arm_1|first_visit_arm_2|baseline_arm_3|baseline_arm_5"
    )
  ) %>% 
  mutate(
    case = 
      if_else(
        str_detect(redcap_event_name, "baseline_arm_1|first_visit_arm_2")
        , "Case"
        , "Cohort"
      )
  )
```

### Data Vis 

#Age Distribution of cases
```{r}
cases %>% 
  ggplot(aes(x = age_final)) +
  geom_vline(aes(xintercept = median(age_final, na.rm = TRUE)), size = 2) +
  geom_histogram(
    binwidth = 2,
    boundary = 0,
    color = "black",
    fill = "red") + 
  annotate("text", x = 30, y = 65, size = 6, label = "Median age \n 20.7 yrs") +
  scale_x_continuous(breaks = scales::breaks_width(10)) +
  labs(
    title = "Age Distribution of Typhoid Cases",
    x = "Age (yrs)",
    y = "Number of Cases"
  ) 

ggsave(ages_plot)



```


## Case Sex 
```{r}
cases %>% 
  count(sex) %>% 
  mutate(proportion =  n / sum(n))

```


```{r}
cases %>% 
  count(hftoiletshare) %>% 
  mutate(proportion =  n / sum(n))

View(cases)
```
# Percentage that uses mostly unimproved water 
```{r}
cases %>% 
  count(hfdrwater) %>% 
  drop_na() %>% 
  mutate(proportion =  n / sum(n))
```

#Proportion that treats drinking water 
```{r}
cases %>% 
  count(hftreatdkwater) %>% 
  drop_na() %>% 
  mutate(proportion =  n / sum(n))

#I didnt pull this record like I should have 
# cases %>% 
#   filter(hftreatdkwater == 1) %>% 
#   count(hftreatfreq) %>% 
#   drop_na() %>% 
#   mutate(proportion =  n / sum(n))

```
```{r}
cases %>% 
  count(receivevacc) %>% 
  drop_na() %>% 
  mutate(proportion =  n / sum(n))
```
## Making Table 1 from the case cohort data 

```{r}
sex_recode <- 
  c(
    "1" = "Male",
    "2" = "Female",
    .default = NA_character_
  )
toilet_share_recode <- 
  c(
    "0" = "No",
    "1" = "Yes", 
    .default = NA_character_
  )

water_type_recode <- 
  c(
    "1" = "piped water",
    "2" = "piped water",
    "3" = "improved well",
    "4" = "improved well",
    "6" = "unimproved well", 
    .default = NA_character_
  )

ses_recode <- 
  c(
    "1" = "<15000 Ruppee",
    "2" = "15000-30000",
    "3" = "30000-50000",
    "4" = ">50000", 
    .default = NA_character_
  )


list_vars <- c("Age", "Gender", "Toilet Sharing with > 1 Family", "Family Monthly Income", "Water Source", "Household treats drinking water", "Previously recieved typhoid vaccine")
cat_vars <- c( "Gender", "Toilet Sharing with > 1 Family", "Family Monthly Income", "Water Source", "Household treats drinking water", "Previously recieved typhoid vaccine")


case_cohort %>% 
  filter(
    str_detect(index_id, "Dummy") == FALSE, 
         !is.na(sex)
         ) %>%
  group_by(index_id) %>% 
  slice(1) %>% 
  mutate(
    `Age` = age_final,
    Gender = recode(sex, !!! sex_recode), 
    `Toilet Sharing with > 1 Family` = recode(hftoiletshare, !!! toilet_share_recode),
    `Family Monthly Income` = recode(hf_famincome_nepal, !!! ses_recode),
    `Water Source` = recode(hfdrwater, !!! water_type_recode), 
    `Household treats drinking water` = recode(hftreatdkwater, !!! toilet_share_recode),
    `Previously recieved typhoid vaccine` = recode(receivevacc, !!! toilet_share_recode)
  ) %>% 
  CreateTableOne(
    vars = list_vars,
    factorVars = cat_vars,
    strata = "case",
     ) %>% 
  print(exact = "stage", quote = FALSE, noSpaces = TRUE)



#mutate(case_type = recode(case_type, !!! vars_cases_recode))

case_cohort %>% 
  count(index_id) %>% 
  arrange(desc(n))

```


