---
title: "River Water Analysis: Andrews Lab"
author: "Chris LeBoa"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Set dates for water metadata 
min <- as.Date("2019-11-15")
max <- NA

bimonthly <- function(x) {
  x_range <- range(x, na.rm = TRUE)
  date_range <- c(
    floor_date(x_range[1], "month"),
    ceiling_date(x_range[2], "month")
  )
  monthly <- seq(date_range[1], date_range[2], by = "1 month")
  sort(c(monthly + days(14)))
}

yes_no_recode <- 
  c(
    "1" = "Contaminated", 
    "0" = "Not Contaminated"
  )
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)
library(RCurl)
library(lubridate)

# Redcap API 

#For drinking water dates 
sees_nepal_data <- postForm(
  uri='https://redcap.stanford.edu/api/',
  token='1F2BCB605944BE0455E5CEA4FB4DE65E',
  content='report',
  format='csv',
  report_id='57256',
  csvDelimiter='',
  rawOrLabel='raw',
  rawOrLabelHeaders='raw',
  exportCheckboxLabel='false',
  returnFormat='csv'
)
#For River Positivity Analysis 
river_nepal_data <- postForm(
  uri='https://redcap.stanford.edu/api/',
  token='E7E4D521E860D283CC17037378399BA0',
  content='report',
  format='csv',
  report_id='74088',
  csvDelimiter='',
  rawOrLabel='raw',
  rawOrLabelHeaders='raw',
  exportCheckboxLabel='false',
  returnFormat='csv'
)

#read in data
nepal_sees_data <- read_csv(sees_nepal_data)
nepal_river_data <- read_csv(river_nepal_data)

#Parameters
pcr_threshold <- 35
#===============================================================================

```

## Water Date 
```{r}
nepal_sees_data %>% 
  mutate(water_week = floor_date(water_date, unit = "week")) %>% 
  ggplot(aes(x = water_week)) +
  geom_bar(fill = "light blue", color = "black") +
  scale_x_date(date_breaks = "2 months", date_labels = "%B %Y") +
  labs(
    title = "Drinking water collection timeline",
    y = "Number of Samples", 
    x = "Week of the year"
  )
```


### River Positivity over time

#### Typhi
```{r, fig.asp=1, warning=FALSE}
nepal_river_data_formatted <- 
  nepal_river_data %>%
  mutate_at(
    vars(matches("river_pcr")),
    ~as.double(recode(., "UD" = "99", .default = .)
    )) %>% 
  mutate(
    typhi_pos = 
      if_else(
        river_pcr_typhi_1_t16_ct < 35 | river_pcr_typhi_2_t16_ct < 35, "Pos", "Neg"),
    paratyphi_pos = 
      if_else(
        river_pcr_paratyphi_1_t16_ct  < 35 | river_pcr_paratyphi_1_t16_ct < 35,
        "Pos",
        "Neg"
        ),
    typhi_border = 
      case_when(
        river_pcr_paratyphi_1_t16_ct  < 35 | river_pcr_paratyphi_1_t16_ct < 35 ~ "Pos", 
        (river_pcr_paratyphi_1_t16_ct  > 35 & river_pcr_paratyphi_1_t16_ct  < 40) | 
          (river_pcr_paratyphi_1_t16_ct  > 35 & river_pcr_paratyphi_1_t16_ct  < 40) ~ "Border", 
        TRUE ~ "Neg"
      ),
    sample_date = floor_date(as_date(river_datetime), "week")
  ) %>% 
  drop_na(typhi_pos)

nepal_river_data_formatted %>% 
  ggplot() +
  geom_point(
    aes(x = sample_date, y = sample_id, fill = as_factor(typhi_pos)),
    shape = 21, size = 6
    ) +
  scale_x_date(date_breaks = "2 months", date_labels = "%B %Y") +
  scale_fill_manual(values = c("chartreuse3", "red")) +
  theme(
    legend.position = "top",
    legend.text = element_text(size = 16),
    axis.text.y = element_text(size = 16), 
    axis.text.x = element_text(size = 12)
    ) + 
  labs(
    title = "S.Typhi River Water Results",
    y = "", 
    x = "", 
    fill = ""
  )
  
## Test with border
nepal_river_data_formatted %>% 
  ggplot() +
  geom_point(
    aes(x = sample_date, y = sample_id, fill = as_factor(typhi_border)),
    shape = 21, size = 6
    ) +
  scale_x_date(date_breaks = "2 months", date_labels = "%B %Y") +
  scale_fill_manual(values = c("chartreuse3", "red", "yellow" )) +
  theme(
    legend.position = "top",
    legend.text = element_text(size = 16),
    axis.text.y = element_text(size = 16), 
    axis.text.x = element_text(size = 12)
    ) + 
  labs(
    title = "S.Typhi River Water Results",
    y = "", 
    x = "", 
    fill = ""
  )
  



```
Typhi Positives by month
```{r}
nepal_river_data_formatted %>% 
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
  mutate(
    sample_week = floor_date(sample_date, "week"),    
    redcap_event_name = str_replace_all(str_extract(redcap_event_name, "[^a]+"), "_", " "), 
    ) %>% 
  group_by(redcap_event_name) %>% 
  count(typhi_pos) %>% 
  filter(typhi_pos == "Pos") %>% 
  ggplot() + 
  geom_col(aes(redcap_event_name, n)) + 
  geom_hline(yintercept = 19, color = "blue") +
  theme(axis.text.x = element_text(angle = 45, vjust = .8)) + 
  labs(
    y = "Number of Positive Locations", 
    x = "Sampling Trip"
  ) 
  


```



#### Paratyphi
```{r, fig.asp=1, warning=FALSE}
nepal_river_data %>%
  mutate_at(
    vars(matches("river_pcr")),
    ~as.double(recode(., "UD" = "99", .default = .)
    )) %>% 
  mutate(
    typhi_pos = 
      if_else(
        river_pcr_typhi_1_t16_ct < 35 | river_pcr_typhi_2_t16_ct < 35, "Pos", "Neg"),
    paratyphi_pos = 
      if_else(
        river_pcr_paratyphi_1_t16_ct  < 35 | river_pcr_paratyphi_1_t16_ct < 35,
        "Pos",
        "Neg"
        ), 
    sample_date = floor_date(as_date(river_datetime), "week")
  ) %>% 
  drop_na(paratyphi_pos) %>% 
  ggplot() +
  geom_point(
    aes(x = sample_date, y = sample_id, fill = as_factor(paratyphi_pos)),
    shape = 21, size = 6
    ) +
  scale_x_date(date_breaks = "2 months", date_labels = "%B %Y") +
  scale_fill_manual(values = c("chartreuse3", "red")) +
  theme(
    legend.position = "top",
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 16), 
    axis.text.x = element_text(size = 12)
    ) + 
  labs(
    title = "S.Paratyphi River Water Results",
    y = "Sample Location", 
    x = "", 
    fill = ""
  )
```
Paratyphi Positives by month
```{r}
nepal_river_data_formatted %>% 
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
  mutate(
    sample_week = floor_date(sample_date, "week"),    
    redcap_event_name = str_replace_all(str_extract(redcap_event_name, "[^a]+"), "_", " "), 
    ) %>% 
  group_by(redcap_event_name) %>% 
  count(paratyphi_pos) %>% 
  filter(paratyphi_pos == "Pos") %>% 
  ggplot() + 
  geom_col(aes(redcap_event_name, n)) + 
  geom_hline(yintercept = 19, color = "blue") +
  theme(axis.text.x = element_text(angle = 45, vjust = .8)) + 
  labs(
    y = "Number of Positive Locations", 
    x = "Sampling Trip"
  ) 
  
```

#Color on replication value 

```{r, fig.asp=.7, warning=FALSE}
nepal_river_data %>%
  mutate_at(
    vars(matches("river_pcr")),
    ~as.double(recode(., "UD" = "99", .default = .)
    )) %>% 
  mutate(
    typhi_pos = 
      if_else(
        river_pcr_typhi_1_t16_ct < 35 | river_pcr_typhi_2_t16_ct < 35, "Pos", "Neg"),
    paratyphi_pos = 
      if_else(
        river_pcr_paratyphi_1_t16_ct  < 35 | river_pcr_paratyphi_1_t16_ct < 35,
        "Pos",
        "Neg"
        ), 
    paratyphi_pos_num = if_else(
       river_pcr_paratyphi_1_t16_ct  > 35, 
       41, 
       river_pcr_paratyphi_1_t16_ct
    ),
    sample_date = floor_date(as_date(river_datetime), "week")
  ) %>% 
  drop_na(paratyphi_pos) %>% 
  ggplot() +
  geom_point(
    aes(x = sample_date, y = sample_id, fill = paratyphi_pos_num),
    shape = 21, size = 6
    ) +
  scale_x_date(date_breaks = "2 months", date_labels = "%B %Y") +
  scale_fill_gradient2(
    midpoint = 32,
    low = "dark green",
    mid = "yellow",
    high = "red", 
    breaks = c(29, 32, 35, 40), 
    labels = c(29, 32, 35, "Neg.")
    ) +
   theme(
    legend.position = "top",
    legend.text = element_text(size = 12),
    axis.text.y = element_text(size = 16), 
    axis.text.x = element_text(size = 12)
    ) + 
  labs(
    title = "S.Paratyphi River Water Results",
    y = "", 
    x = "", 
    fill = ""
  )
```
#Abiotic Factors 

##Temperature 
```{r}
nepal_river_data_formatted %>% 
  filter(river_orp < 0) %>%
  #mutate(typhi_pos_t16 = recode(typhi_pos_t16, !!! yes_no_recode)) %>% 
  ggplot(aes(as.Date(river_datetime), river_temp)) +
  geom_hline(aes(yintercept = mean(river_temp, na.rm = TRUE)), color = "blue") +
  geom_smooth(
    aes(
      color =  as.factor(typhi_pos), fill = as.factor(typhi_pos)
    ),
    method = "loess"
  ) +
  geom_point(aes(color = as.factor(typhi_pos))) + 
  scale_x_date(date_breaks = "2 months", date_labels = "%B", limits = c(min, max)) +
  guides(fill = FALSE) +
  theme(legend.position = "bottom") +
  labs(
    x = "", 
    y = "River Temp (deg. C)",
    color = "Contamination with S.Typhi"
  )

nepal_river_data_formatted %>% 
  filter(river_orp < 0) %>% 
  ggplot(aes(typhi_pos,river_temp, color = typhi_pos)) +
  geom_boxplot() + 
  theme(legend.position = "none") +
  labs(
    x = "Contamination with S.Typhi", 
    y = "River Temp (deg. C)"
  )

  
```
##Turbidity
```{r}


nepal_river_data_formatted %>% 
  filter(river_orp < 0) %>%
  #mutate(typhi_pos_t16 = recode(typhi_pos_t16, !!! yes_no_recode)) %>% 
  ggplot(aes(as.Date(river_datetime), river_turbidity)) +
  geom_hline(aes(yintercept = mean(river_turbidity, na.rm = TRUE)), color = "blue") +
  geom_smooth(
    aes(
      color =  as.factor(typhi_pos), fill = as.factor(typhi_pos)
    ),
    method = "loess"
  ) +
  geom_point(aes(color = as.factor(typhi_pos))) + 
  scale_x_date(date_breaks = "2 months", date_labels = "%B", limits = c(min, max)) +
  guides(fill = FALSE) +
  theme(legend.position = "bottom") +
  labs(
    title = "Turbidity and S.Typhi Positivity",
    x = "", 
    y = "River Turbidity",
    color = "Contamination with S.Typhi"
  )


  
```
##ORP
```{r}


nepal_river_data_formatted %>% 
  filter(river_orp < 0) %>%
  #mutate(typhi_pos_t16 = recode(typhi_pos_t16, !!! yes_no_recode)) %>% 
  ggplot(aes(as.Date(river_datetime), river_orp)) +
  geom_hline(aes(yintercept = mean(river_orp, na.rm = TRUE)), color = "blue") +
  geom_smooth(
    aes(
      color =  as.factor(typhi_pos), fill = as.factor(typhi_pos)
    ),
    method = "loess"
  ) +
  geom_point(aes(color = as.factor(typhi_pos))) + 
  scale_x_date(date_breaks = "2 months", date_labels = "%B", limits = c(min, max)) +
  guides(fill = FALSE) +
  theme(legend.position = "bottom") +
  labs(
    title = "Oxygen Reduction Potential and S.Typhi Contamination",
    x = "", 
    y = "River ORP (mV)",
    color = "Contamination with S.Typhi"
  )

```


##pH
```{r}


nepal_river_data_formatted %>% 
  filter(river_orp < 0) %>%
  #mutate(typhi_pos_t16 = recode(typhi_pos_t16, !!! yes_no_recode)) %>% 
  ggplot(aes(as.Date(river_datetime), river_ph)) +
  geom_hline(aes(yintercept = mean(river_ph, na.rm = TRUE)), color = "blue") +
  geom_smooth(
    aes(
      color =  as.factor(typhi_pos), fill = as.factor(typhi_pos)
    ),
    method = "loess"
  ) +
  geom_point(aes(color = as.factor(typhi_pos))) + 
  scale_x_date(date_breaks = "2 months", date_labels = "%B", limits = c(min, max)) +
  guides(fill = FALSE) +
  theme(legend.position = "bottom") +
  labs(
    title = "pH and S.Typhi Positivity",
    x = "", 
    y = "River pH",
    color = "Contamination with S.Typhi"
  )

```
#Positivity Count
```{r}
nepal_river_data_formatted %>% 
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
  group_by(sample_id) %>% 
  summarise(
    typhi_total = sum(typhi_pos == "Pos", na.rm = TRUE),
    paratyphi_total = sum(paratyphi_pos == "Pos", na.rm = TRUE)
  ) %>% 
  write_csv("/Users/ChrisLeBoa/GitHub/typhoid_research/nepal_typhoid/data/rivers/pos.csv")
```

#COUNT DNA and Phage 
```{r}
##Typhi 
nepal_river_data_formatted %>%
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
    group_by(sample_id) %>% 
  summarise(
    typhi_total = sum(typhi_pos == "Pos", na.rm = TRUE),
    paratyphi_total = sum(paratyphi_pos == "Pos", na.rm = TRUE), 
    typhi_phage_total = sum(river_phage_typhi, na.rm = TRUE)
  ) %>% 
  mutate(
    mapping_typhi_DNA = typhi_total, 
    mapping_paratyphi_DNA = paratyphi_total
  ) %>% 
  pivot_longer(
    cols = starts_with("typhi"), 
    names_to = "typhi",
    values_to = "sample_trips_positive"
  ) %>% 
  mutate(
    typhi =
      if_else(str_detect(typhi, "phage") == TRUE, "phage", "DNA")
  ) %>% 
  ggplot(aes(x = reorder(sample_id, c(-mapping_typhi_DNA)))) +
  geom_col(
    aes(
      y = sample_trips_positive, fill = typhi),
    position = position_dodge(width=0.7),
    width = .7
  ) +
  geom_hline(aes(yintercept = 13), color = "grey60") +
  theme(
    legend.position = "bottom", 
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(
    title = "Sampling Points Positive for S. Typhi", 
    x = "Sampling Location",
    y = "Positive results from first 13 trips", 
    fill = "Type of Contamination"
  )

## Paratyphi
nepal_river_data_formatted %>%
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
    group_by(sample_id) %>% 
  summarise(
    typhi_total = sum(typhi_pos == "Pos", na.rm = TRUE),
    paratyphi_total = sum(paratyphi_pos == "Pos", na.rm = TRUE), 
    typhi_phage_total = sum(river_phage_typhi, na.rm = TRUE), 
    paratyphi_phage_total = sum(river_phage_paratyphi, na.rm = TRUE)
  ) %>% 
  mutate(
    mapping_typhi_DNA = typhi_total, 
    mapping_paratyphi_DNA = paratyphi_total
  ) %>% 
  pivot_longer(
    cols = starts_with("para"), 
    names_to = "paratyphi",
    values_to = "sample_trips_positive"
  ) %>% 
  mutate(
    paratyphi =
      if_else(str_detect(paratyphi, "phage") == TRUE, "phage", "DNA")
  ) %>% 
  ggplot(aes(x = reorder(sample_id, c(-mapping_paratyphi_DNA)))) +
  geom_col(
    aes(
      y = sample_trips_positive, fill = paratyphi),
    position = position_dodge(width=0.7),
    width = .7
  ) +
  geom_hline(aes(yintercept = 13), color = "grey60") +
  theme(
    legend.position = "bottom", 
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(
    title = "Sampling Points Positive for S. Paratyphi", 
    x = "Sampling Location",
    y = "Positive results from first 13 trips", 
    fill = "Type of Contamination"
  )
```


```{r}
nepal_river_data_formatted %>%
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
  #  group_by(sample_id) %>% 
  summarise(
    typhi_total = sum(typhi_pos == "Pos", na.rm = TRUE),
    paratyphi_total = sum(paratyphi_pos == "Pos", na.rm = TRUE), 
    typhi_phage_total = sum(river_phage_typhi, na.rm = TRUE), 
    paratyphi_phage_total = sum(river_phage_paratyphi, na.rm = TRUE)
  )
```
#Phage and Coliform Counts
```{r}
nepal_river_data_formatted %>% 
  filter(
    is.na(redcap_repeat_instance) | redcap_repeat_instance == 1, 
    !is.na(river_e_coli_count)
    ) %>% 
  ggplot(aes(as.Date(river_datetime), river_e_coli_count)) +
  geom_point(aes(color = sample_id)) + 
  geom_smooth() + 
  scale_y_continuous(labels = scales::label_comma()) +
  labs(
   title =  "Coliform Contamination over Time", 
   x = "", 
   y = "Coliform Count (colonies per mL)"
  )

nepal_river_data_formatted %>% 
  filter(
    is.na(redcap_repeat_instance) | redcap_repeat_instance == 1, 
    !is.na(river_e_coli_count)
    ) %>% 
  mutate(
    sample_week = floor_date(sample_date, "week"),    
    redcap_event_name = str_replace_all(str_extract(redcap_event_name, "[^a]+"), "_", " "), 
    ) %>% 
  ggplot(aes(redcap_event_name, river_e_coli_count)) +
  geom_boxplot() + 
  geom_point(aes(color = sample_id)) + 
  scale_y_continuous(labels = scales::label_comma()) +
  theme(axis.text.x = element_text(angle = 45, vjust = .8)) + 
  labs(
   title =  "Coliform Contamination over Time", 
   x = "", 
   y = "Coliform Count (colonies per mL)"
  )

nepal_river_data_formatted %>% 
  ggplot(aes(redcap_event_name, river_phage_typhi_count, color = redcap_event_name)) +
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 45, vjust = .8)) 

nepal_river_data_formatted %>% 
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
  mutate(
    sample_week = floor_date(sample_date, "week"),    
    redcap_event_name = str_replace_all(str_extract(redcap_event_name, "[^a]+"), "_", " "), 
    ) %>% 
  pivot_longer(cols = c(river_phage_paratyphi, river_phage_typhi), names_to = "organism", values_to = "phage") %>% 
  group_by(redcap_event_name, organism) %>% 
  count(phage) %>% 
  filter(phage == 1) %>% 
  ggplot() + 
  geom_col(aes(redcap_event_name, n, fill = organism), position = "dodge") + 
  geom_hline(yintercept = 19, color = "blue") +
  theme(axis.text.x = element_text(angle = 45, vjust = .8)) + 
  labs(
    title = "Phage presence by Sampling Trip", 
    y = "Number of Positive Locations", 
    x = "Sampling Trip"
  ) 
  
nepal_river_data_formatted %>% 
  filter(is.na(redcap_repeat_instance) | redcap_repeat_instance == 1) %>% 
  filter(sample_id %in% c("COM-1", "COM-2", "COM-3", "BAG-1")) %>% 
  ggplot(aes(as.Date(river_datetime), river_phage_paratyphi_count, color = sample_id)) +
  geom_point() +
  geom_smooth(se=F) + 
  labs(
    title = "Number of S.Paratyphi Phages in Always Positive Sites", 
    x = "Date", 
    y = "Phage Count"
  )

```
```{r}
nepal_river_data_formatted %>% 
  filter(river_sewer_draining > 0) %>% 
  count(sample_id)

nepal_river_data_formatted %>% 
  filter(river_bathing == 1) %>% 
  count(sample_id)

nepal_river_data_formatted %>% 
  filter(river_walk_across == 1) %>% 
  count(sample_id)

nepal_river_data_formatted %>% 
  filter(river_wash_veg == 1) %>% 
  count(sample_id, typhi_pos, paratyphi_pos)

nepal_river_data_formatted %>% 
  filter(river_feces == 1) %>% 
  count(sample_id)

nepal_river_data_formatted %>% 
  filter(river_wash_clothes == 1) %>% 
  count(river_wash_clothes_reason)

nepal_river_data_formatted %>% 
  filter(river_agriculture == 1) %>% 
  count(sample_id)

nepal_river_data_formatted %>% 
  mutate(active_sewage = case_when(
    river_sewer_draining > 0 ~  1, 
    is.na(river_sewer_draining) ~ 0,
    TRUE ~ 0), 
    ) %>% 
  count(active_sewage, typhi_pos)
  ggplot(aes(river_date, typhi_pos, color = active_sewage))
  
  

  
```

