---
title: "River_Sampling_Processing"
author: "Chris LeBoa"
date: "1/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Load Packages}
library(tidyverse)
library(readxl)
```

```{r}
df <- 
  read_excel("/Users/ChrisLeBoa/Documents/Stanford School Files /Research/Andrews Lab/Dtata_RiverSampling/Nepal_RiverSampling_Compilation_Nov_Jan.xlsx")
```


#Convert data to tidy form

```{r}
#view(df)

df_longer <- 
  df %>% 
  pivot_longer(
    cols = -location,
    names_to = "sampling_time",
    values_to = "ct_value"
  ) %>% 
  separate(sampling_time, c("species", "time"), "_")

df_longer
```
#Count number of times positive at each position

```{r}
df_totals <- 
  df_longer %>% 
  mutate(ct_value = ifelse(ct_value < 35, 1, 0)) %>%
  group_by(location, species) %>% 
  summarise(n_ctpos = sum(ct_value))

df_totals %>% 
  group_by(species) %>% 
  summarise(pos = sum(n_ctpos))
```

#Write seperate datasets for S.Typhi and S. Paratyphi 
```{r}
#Typhi
df_totals %>% 
  filter(species == "St") %>% 
  write_csv("/Users/ChrisLeBoa/Documents/Stanford School Files /Research/Andrews Lab/Dtata_RiverSampling/STyphi_Totals_Nepal_RiverSampling_Nov_Jan.csv")


df_totals %>% 
  filter(species == "Spt") %>% 
  write_csv("/Users/ChrisLeBoa/Documents/Stanford School Files /Research/Andrews Lab/Dtata_RiverSampling/SParatyphi_Totals_Nepal_RiverSampling_Nov_Jan.csv")



```

